build:
  info:
    file: classpath:build-info.yml
server:
  servlet:
    contextPath: /api

swagger:
  api:
    title: sample-api
    contact.info: Team
    licence.url: #
    description:
    groupName: sample-api
    version: 1.0
    path:
      regex: /v.*/.*
  terms.of.service.url: #
  enabled: true

request:
  logging:
    enabled: true
    verbose: false

  
security:
  enable-csrf: false
  

spring:
  rabbitmq:
    uri: amqp://opwcbexo:5IZ6Ll-lDVKNXQUJBIwghURM9AlIr2Tw@moose.rmq.cloudamqp.com/opwcbexo
    queue.name: "TSP.EmailNotification.Payload.Queue"
            
SendGrid_API_KEY: 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
