spring.thymeleaf.cache: false

build:
  info:
    file: classpath:build-info.yml
server:
  servlet:
    contextPath: /api

swagger:
  api:
    title: sample-api
    contact.info: Team
    licence.url: #
    description:
    groupName: sample-api
    version: 1.0
    path:
      regex: /v.*/.*
  terms.of.service.url: #
  enabled: true

spring:
    main:
        allow-bean-definition-overriding: true

    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/tsp_subscriber
      username: root
      password: admin
    jpa:
      hibernate.ddl-auto: update
      generate-ddl: true
      show-sql: true
    rabbitmq:
      uri: amqp://opwcbexo:5IZ6Ll-lDVKNXQUJBIwghURM9AlIr2Tw@moose.rmq.cloudamqp.com/opwcbexo

request:
  logging:
    enabled: true
    verbose: false
security:
    enable-csrf: false
    
adminBaseUrl: https://tsp-admin-service.cfapps.io/api/
